#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Export engagement journals (+ optional COA) to a Beancount ledger (system of record).

Excel/workpapers = engagement working papers.
Beancount = plain-text double-entry ledger (final boss after books are solid).
Fava = UI over the .beancount file.

Usage:
  python3 scripts/export_to_beancount.py \\
    --client-dir fixtures/golden-mini-sdn-bhd \\
    --output fixtures/golden-mini-sdn-bhd/ledger/main.beancount

  python3 scripts/export_to_beancount.py \\
    --journals workpapers/journals.json \\
    --journals-ye workpapers/journals_ye.json \\
    --coa references/coa_templates/coa_sdn_bhd.json \\
    --currency MYR \\
    --title "Client Ledger" \\
    --output ledger/main.beancount \\
    --bean-check

Requires: Python 3.10+. Optional: beancount (bean-check) for validation.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from decimal import Decimal
from pathlib import Path
from typing import Any


TYPE_ROOT = {
    "Asset": "Assets",
    "Liability": "Liabilities",
    "Equity": "Equity",
    "Revenue": "Income",
    "Income": "Income",
    "Expense": "Expenses",
    # fallbacks
    "asset": "Assets",
    "liability": "Liabilities",
    "equity": "Equity",
    "revenue": "Income",
    "expense": "Expenses",
}


def money(x: Any) -> Decimal:
    return Decimal(str(x or 0)).quantize(Decimal("0.01"))


def slug_account_part(name: str) -> str:
    """Beancount account component: letters, digits, dash."""
    s = name.strip()
    s = s.replace("&", "And")
    s = re.sub(r"[^\w\s\-]", "", s, flags=re.UNICODE)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    if not s:
        s = "Unknown"
    # Beancount wants components to start with uppercase letter typically
    if s[0].isdigit():
        s = "A" + s
    return s[:64]


def code_to_beancount(code: str, name: str, acct_type: str) -> str:
    root = TYPE_ROOT.get(acct_type, TYPE_ROOT.get(str(acct_type).capitalize(), "Equity"))
    # Assets:Bank:Cash-And-Bank-1000
    part = slug_account_part(name)
    return f"{root}:{part}-{code}"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def load_coa(path: Path | None) -> dict[str, dict]:
    if not path or not path.is_file():
        return {}
    data = load_json(path)
    if "accounts" in data:
        return {str(k): v for k, v in data["accounts"].items()}
    # flat map code -> {name, type}
    return {str(k): v for k, v in data.items() if isinstance(v, dict)}


def resolve_account(
    code: str,
    name: str | None,
    coa: dict[str, dict],
    cache: dict[str, str],
) -> str:
    if code in cache:
        return cache[code]
    meta = coa.get(str(code), {})
    acct_name = name or meta.get("name") or f"Account-{code}"
    acct_type = meta.get("type") or "Equity"
    bc = code_to_beancount(str(code), acct_name, acct_type)
    cache[code] = bc
    return bc


def collect_journals(paths: list[Path]) -> list[dict]:
    journals: list[dict] = []
    for p in paths:
        if not p or not p.is_file():
            continue
        data = load_json(p)
        journals.extend(data.get("journals") or [])
    return journals


def open_date_from_journals(journals: list[dict], fallback: str = "1970-01-01") -> str:
    dates = [j.get("date") for j in journals if j.get("date")]
    return min(dates) if dates else fallback


def build_beancount(
    *,
    title: str,
    currency: str,
    coa: dict[str, dict],
    journals: list[dict],
    operating_currency: str | None = None,
    plugin_pad: bool = False,
) -> str:
    cur = currency
    op_cur = operating_currency or currency
    account_map: dict[str, str] = {}
    accounts_needed: dict[str, str] = {}  # bc_name -> open date

    # Pre-register COA
    for code, meta in coa.items():
        bc = resolve_account(code, meta.get("name"), coa, account_map)
        accounts_needed[bc] = "1970-01-01"

    # Scan journals for accounts
    open_d = open_date_from_journals(journals)
    for je in journals:
        for line in je.get("lines") or []:
            code = str(line.get("account_code") or "")
            name = line.get("account_name")
            if not code:
                continue
            bc = resolve_account(code, name, coa, account_map)
            if bc not in accounts_needed:
                accounts_needed[bc] = open_d

    # Always ensure equity opening pad target if used later
    lines_out: list[str] = []
    lines_out.append(f"; Beancount ledger generated by claude-for-accounting")
    lines_out.append(f"; title: {title}")
    lines_out.append(f"option \"title\" \"{title}\"")
    lines_out.append(f"option \"operating_currency\" \"{op_cur}\"")
    lines_out.append("")
    if plugin_pad:
        lines_out.append('plugin "beancount.plugins.auto_accounts"')
        lines_out.append("")

    # Open accounts
    for bc in sorted(accounts_needed.keys()):
        d = accounts_needed[bc]
        lines_out.append(f"{d} open {bc} {cur}")
    lines_out.append("")

    # Transactions from journals
    errors: list[str] = []
    for je in sorted(journals, key=lambda j: (j.get("date") or "", j.get("je_number") or "")):
        date = je.get("date") or open_d
        narr = (je.get("narration") or je.get("description") or je.get("je_number") or "Journal").replace(
            '"', "'"
        )
        je_no = je.get("je_number") or ""
        source = je.get("source_ref") or ""
        meta_tags = []
        if je_no:
            meta_tags.append(f'  je: "{je_no}"')
        if source:
            meta_tags.append(f'  source: "{str(source).replace(chr(34), chr(39))}"')

        je_lines = je.get("lines") or []
        # balance check
        deb = sum((money(L.get("debit")) for L in je_lines), Decimal("0"))
        cre = sum((money(L.get("credit")) for L in je_lines), Decimal("0"))
        if deb != cre:
            errors.append(f"{je_no or date}: unbalanced JE DR={deb} CR={cre}")

        lines_out.append(f'{date} * "{narr}"')
        lines_out.extend(meta_tags)

        for L in je_lines:
            code = str(L.get("account_code") or "")
            name = L.get("account_name")
            bc = resolve_account(code, name, coa, account_map)
            d = money(L.get("debit"))
            c = money(L.get("credit"))
            # Beancount: positive increases account depending on type is not automatic —
            # we post signed amounts: debit positive on Assets/Expenses, credit positive as negative amount
            # Standard approach: amount is signed for the posting
            # DR -> +amount, CR -> -amount (Beancount balances sum to zero)
            if d > 0 and c > 0:
                errors.append(f"{je_no}: line both debit and credit")
                continue
            if d > 0:
                amt = d
            elif c > 0:
                amt = -c
            else:
                continue
            # Format:  Assets:Cash  100.00 MYR
            lines_out.append(f"  {bc}  {amt} {cur}")
        lines_out.append("")

    if errors:
        lines_out.insert(0, "; EXPORT WARNINGS:")
        for e in errors:
            lines_out.insert(1, f"; ERROR: {e}")
        lines_out.insert(1 + len(errors), "")

    return "\n".join(lines_out) + "\n", errors, account_map


def discover_client_inputs(client_dir: Path) -> dict[str, Path | None]:
    wp = client_dir / "workpapers"
    return {
        "journals": wp / "journals.json" if (wp / "journals.json").is_file() else None,
        "journals_ye": wp / "journals_ye.json" if (wp / "journals_ye.json").is_file() else None,
        "coa": wp / "coa.json" if (wp / "coa.json").is_file() else None,
        "state": client_dir / "engagement_state.json" if (client_dir / "engagement_state.json").is_file() else None,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="Export journals to Beancount ledger")
    ap.add_argument("--client-dir", type=Path, help="Engagement client folder")
    ap.add_argument("--journals", type=Path, action="append", default=[], help="journals.json (repeatable)")
    ap.add_argument("--journals-ye", type=Path, help="year-end journals json")
    ap.add_argument("--coa", type=Path, help="COA json (entity template or workpapers/coa.json)")
    ap.add_argument("--currency", default="MYR")
    ap.add_argument("--title", default=None)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--bean-check", action="store_true", help="Run bean-check after write")
    ap.add_argument("--allow-unbalanced", action="store_true")
    args = ap.parse_args()

    journal_paths: list[Path] = list(args.journals or [])
    coa_path = args.coa
    title = args.title or "Accounting Ledger"
    currency = args.currency

    if args.client_dir:
        found = discover_client_inputs(args.client_dir)
        if found["journals"]:
            journal_paths.append(found["journals"])
        if found["journals_ye"]:
            journal_paths.append(found["journals_ye"])
        if args.journals_ye:
            journal_paths.append(args.journals_ye)
        if not coa_path and found["coa"]:
            coa_path = found["coa"]
        if found["state"]:
            st = load_json(found["state"])
            title = args.title or st.get("legal_name") or title
            currency = st.get("currency") or currency
        # default coa from entity if still missing — try sdn bhd template relative to repo
        if not coa_path:
            repo = Path(__file__).resolve().parents[1]
            guess = repo / "references/coa_templates/coa_sdn_bhd.json"
            if guess.is_file():
                coa_path = guess
    elif args.journals_ye:
        journal_paths.append(args.journals_ye)

    # dedupe paths
    seen = set()
    uniq_paths = []
    for p in journal_paths:
        rp = p.resolve()
        if rp not in seen and p.is_file():
            seen.add(rp)
            uniq_paths.append(p)

    if not uniq_paths:
        print("ERROR: no journals.json found", file=sys.stderr)
        return 1

    coa = load_coa(coa_path)
    journals = collect_journals(uniq_paths)
    if not journals:
        print("ERROR: journals empty", file=sys.stderr)
        return 1

    text, errors, account_map = build_beancount(
        title=title,
        currency=currency,
        coa=coa,
        journals=journals,
    )

    if errors and not args.allow_unbalanced:
        print("ERROR: unbalanced or invalid journals:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        print("Fix journals or pass --allow-unbalanced (not recommended).", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"Wrote {args.output}")
    print(f"  journals: {len(journals)}")
    print(f"  accounts: {len(account_map)}")
    if errors:
        print(f"  warnings: {len(errors)}")

    # sidecar map for agents
    map_path = args.output.parent / f"{args.output.name}.account_map.json"
    map_path.write_text(json.dumps(account_map, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {map_path}")

    if args.bean_check:
        bean_check = None
        for candidate in ("bean-check", str(Path.home() / "Library/Python/3.12/bin/bean-check")):
            # try PATH first
            pass
        try:
            r = subprocess.run(
                ["bean-check", str(args.output)],
                capture_output=True,
                text=True,
            )
        except FileNotFoundError:
            # common user install path on macOS
            alt = Path.home() / "Library/Python/3.12/bin/bean-check"
            if alt.is_file():
                r = subprocess.run([str(alt), str(args.output)], capture_output=True, text=True)
            else:
                print("WARN: bean-check not found on PATH; skip validation", file=sys.stderr)
                return 0
        if r.returncode != 0:
            print(r.stdout)
            print(r.stderr, file=sys.stderr)
            print("bean-check FAILED", file=sys.stderr)
            return 1
        print("bean-check PASS")

    print("Next: fava", args.output)
    print("  fava", args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
